### ISSUE TITLE
Collapsed comments have missing downvote arrow icon.

### ISSUE THREAD

**Issue by markbranly** [markbranly/hacker-news-modern-ui#39]
<img width="774" alt="a comment thread with one collapsed comment followed by visible comment" src="https://github.com/markbranly/hacker-news-modern-ui/assets/78463/f1e8fa82-737e-4911-8ccb-50e2078efac3">

**Comment by markbranly** [comment]
This is the issue:

```CSS
.votelinks.nosee div.votearrow.rotate180 {
    display: none;
}
```
